name: Jekyll CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # We will pull once a day, UTC to start to not blow up our Github actions
    - cron: '30 12 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: docker://ruby:3.3
      env:
        BUNDLE_PATH: .bundle
      with:
        entrypoint: bundle
        args: install -j=4

    - name: Fetch the content
      uses: docker://ruby:3.3
      env:
        BUNDLE_PATH: .bundle
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        LC_ALL: C.UTF-8
      with:
        entrypoint: bundle
        args: exec rake

    - name: Build the site
      uses: docker://ruby:3.3
      env:
        BUNDLE_PATH: .bundle
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        LC_ALL: C.UTF-8
      with:
        entrypoint: bundle
        args: exec jekyll build
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
